package echproxy

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

func isJavascriptResponse(resp *http.Response) bool {
	ct := resp.Header.Get("Content-Type")
	if ct == "" {
		return strings.HasSuffix(resp.Request.URL.Path, ".js")
	}
	return strings.Contains(strings.ToLower(ct), "javascript")
}

func buildSWProxyMap(cfg UpstreamMap, port string) map[string]string {
	m := map[string]string{}
	for entry, uc := range cfg {
		if uc.Host != "" && !strings.Contains(uc.Host, indexHost) {
			target := entry
			if port != "" && !strings.Contains(target, ":") {
				target += ":" + port
			}
			m[uc.Host] = target
		}
		for target, local := range uc.Rewrites {
			if strings.HasPrefix(target, ".") || strings.HasPrefix(target, "*") {
				continue
			}
			if port != "" && !strings.Contains(local, ":") {
				m[target] = local + ":" + port
			} else {
				m[target] = local
			}
		}
	}
	return m
}

func collectWildcardRules(cfg UpstreamMap) []WildcardRule {
	var out []WildcardRule
	seen := map[string]bool{}
	for _, uc := range cfg {
		if uc.Wildcard == nil {
			continue
		}
		key := uc.Wildcard.Prefix + uc.Wildcard.UpstreamSuffix
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, *uc.Wildcard)
	}
	return out
}

func swOverrideJS(m map[string]string, rules []WildcardRule, blockedHosts []string) string {
	b, _ := json.Marshal(m)
	type jsRule struct {
		P  string `json:"p"`
		ES string `json:"es"`
		US string `json:"us"`
	}
	var jrules []jsRule
	for _, r := range rules {
		jrules = append(jrules, jsRule{P: r.Prefix, ES: r.EntrySuffix, US: r.UpstreamSuffix})
	}
	rb, _ := json.Marshal(jrules)
	bb, _ := json.Marshal(blockedHosts)
	return fmt.Sprintf(`// Generated by ech-proxy
const __swMap = %s;
const __swRules = %s;
const __swBlock = %s;

self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));

self.addEventListener('fetch', (e) => {
  try {
    const u = new URL(e.request.url);
    if (__swBlock.some((b) => {
      const bare = b.replace(/^https?:\/\//, '').replace(/^\/\//, '');
      return u.hostname === bare || u.hostname.endsWith('.' + bare) || (u.hostname + u.pathname).startsWith(bare) || e.request.url.startsWith(b);
    })) {
      e.respondWith(new Response('', { status: 204 }));
      return;
    }
    let p = __swMap[u.hostname];
    if (!p) {
      const h = u.hostname;
      for (const r of __swRules) {
        if (h === r.us.slice(1)) {
          p = r.p.slice(0, -1) + r.es;
          break;
        }
        if (h.endsWith(r.us)) {
          const sub = h.slice(0, -r.us.length);
          p = r.p + sub + r.es;
          break;
        }
      }
    }
    if (!p) return;
    const dest = new URL(e.request.url);
    const [pHost, pPort] = p.split(':');
    dest.hostname = pHost;
    if (pPort) dest.port = pPort;
    const req = new Request(dest.toString(), {
      method: e.request.method,
      headers: e.request.headers,
      body: e.request.body,
      mode: 'cors',
      credentials: e.request.credentials,
      cache: e.request.cache,
      redirect: 'manual',
      referrer: e.request.referrer,
      integrity: e.request.integrity,
    });
    e.respondWith(fetch(req));
  } catch (_) {}
});
`, string(b), string(rb), string(bb))
}
